const APPLICATION_NAME_SET = 'APPLICATION_NAME_SET';
const APPLICATION_MENU_OPEN = 'APPLICATION_MENU_OPEN';
const APPLICATION_MENU_CLOSE = 'APPLICATION_MENU_CLOSE';

const APPLICATION_NOTIFICATION_ADD = 'APPLICATION_NOTIFICATION_ADD';
const APPLICATION_NOTIFICATION_SHOW = 'APPLICATION_NOTIFICATION_SHOW';
const APPLICATION_NOTIFICATION_CLOSE = 'APPLICATION_NOTIFICATION_CLOSE';

export {
    APPLICATION_NAME_SET,
    APPLICATION_MENU_OPEN,
    APPLICATION_MENU_CLOSE,
    APPLICATION_NOTIFICATION_ADD,
    APPLICATION_NOTIFICATION_SHOW,
    APPLICATION_NOTIFICATION_CLOSE
}