const APPLICATION_NAME_SET = 'APPLICATION_NAME_SET';
const APPLICATION_MENU_OPEN = 'APPLICATION_MENU_OPEN';
const APPLICATION_MENU_CLOSE = 'APPLICATION_MENU_CLOSE';

export {
    APPLICATION_NAME_SET,
    APPLICATION_MENU_OPEN,
    APPLICATION_MENU_CLOSE
}