// - Import Types
import {
    CREATE_API_SERVICE, CREATE_API_FILTER,
    REQUEST_GETBYFILTER, RECEIVE_GETBYFILTER,
    REQUEST_GETBYID, RECEIVE_GETBYID,
    REQUEST_DELETE, RECEIVE_DELETE,
    REQUEST_PATCH, RECEIVE_PATCH,
    REQUEST_POST, RECEIVE_POST,
    REQUEST_PUT, RECEIVE_PUT,
    EXPIRE_COLLECTION, EXPIRE_ENTITY
} from './types';

// - Import Actions
import {
    CreateApiService,
    CreateApiFilter,
} from './actions';

const types = {
    CREATE_API_SERVICE, CREATE_API_FILTER,
    REQUEST_GETBYFILTER, RECEIVE_GETBYFILTER,
    REQUEST_GETBYID, RECEIVE_GETBYID,
    REQUEST_DELETE, RECEIVE_DELETE,
    REQUEST_PATCH, RECEIVE_PATCH,
    REQUEST_POST, RECEIVE_POST,
    REQUEST_PUT, RECEIVE_PUT,
    EXPIRE_COLLECTION, EXPIRE_ENTITY
};

const actions = {
    CreateApiService,
    CreateApiFilter,
};

export {
    types, actions
};