const CREATE_API_SERVICE = 'CREATE_API_SERVICE';
const CREATE_API_FILTER = 'CREATE_API_FILTER';

const REQUEST_GETBYFILTER = 'REQUEST_GETBYFILTER';
const RECEIVE_GETBYFILTER = 'RECEIVE_GETBYFILTER';

const REQUEST_GETBYID = 'REQUEST_GETBYID';
const RECEIVE_GETBYID = 'RECEIVE_GETBYID';

const REQUEST_DELETE = 'REQUEST_DELETE';
const RECEIVE_DELETE = 'RECEIVE_DELETE';

const REQUEST_PATCH = 'REQUEST_PATCH';
const RECEIVE_PATCH = 'RECEIVE_PATCH';

const REQUEST_POST = 'REQUEST_POST';
const RECEIVE_POST = 'RECEIVE_POST';

const REQUEST_PUT = 'REQUEST_PUT';
const RECEIVE_PUT = 'RECEIVE_PUT';

export {
    CREATE_API_SERVICE, CREATE_API_FILTER,
    REQUEST_GETBYFILTER, RECEIVE_GETBYFILTER,
    REQUEST_GETBYID, RECEIVE_GETBYID,
    REQUEST_DELETE, RECEIVE_DELETE,
    REQUEST_PATCH, RECEIVE_PATCH,
    REQUEST_POST, RECEIVE_POST,
    REQUEST_PUT, RECEIVE_PUT
};