const CREATE_API_SERVICE = 'CREATE_API_SERVICE';
const CREATE_API_FILTER = 'CREATE_API_FILTER';

const REQUEST_DATA = 'REQUEST_DATA';
const RECEIVE_DATA = 'RECEIVE_DATA';

export {
    CREATE_API_SERVICE, CREATE_API_FILTER,
    REQUEST_DATA, RECEIVE_DATA
};