const CREATE_API_SERVICE = 'CREATE_API_SERVICE';
const CREATE_API_FILTER = 'CREATE_API_FILTER';

const REQUEST_DATA = 'REQUEST_DATA';
const RECEIVE_DATA = 'RECEIVE_DATA';

const REQUEST_DELETE_DATA = 'REQUEST_DELETE_DATA';
const RECEIVE_DELETE_DATA = 'RECEIVE_DELETE_DATA';

const REQUEST_PATCH_DATA = 'REQUEST_PATCH_DATA';
const RECEIVE_PATCH_DATA = 'RECEIVE_PATCH_DATA';

const REQUEST_PUT_DATA = 'REQUEST_PUT_DATA';
const RECEIVE_PUT_DATA = 'RECEIVE_PUT_DATA';

const REQUEST_POST_DATA = 'REQUEST_POST_DATA';
const RECEIVE_POST_DATA = 'RECEIVE_POST_DATA';

export {
    CREATE_API_SERVICE, CREATE_API_FILTER,
    REQUEST_DATA, RECEIVE_DATA,
    REQUEST_DELETE_DATA, RECEIVE_DELETE_DATA,
    REQUEST_PATCH_DATA, RECEIVE_PATCH_DATA,
    REQUEST_PUT_DATA, RECEIVE_PUT_DATA,
    REQUEST_POST_DATA, RECEIVE_POST_DATA
};